config/routes.rb
Spoon::Application.routes.draw do
  
  resources :users
  resources :rings

  root to: 'static_pages#home'
  
  match '/faq',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'

end

app/models/ring.rb
# == Schema Information
#
# Table name: rings
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  image       :string(255)
#  category    :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Ring < ActiveRecord::Base
  attr_accessible :category, :description, :image, :name
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  username        :string(255)
#  bio             :text
#  avatar          :string(255)
#  admin           :boolean
#  password_digest :string(255)
#  remember_token  :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :admin, :avatar, :bio, :email, :name, :password_digest, :remember_token, :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/rings_controller.rb
class RingsController < ApplicationController
  # GET /rings
  # GET /rings.json
  def index
    @rings = Ring.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rings }
    end
  end

  # GET /rings/1
  # GET /rings/1.json
  def show
    @ring = Ring.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ring }
    end
  end

  # GET /rings/new
  # GET /rings/new.json
  def new
    @ring = Ring.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ring }
    end
  end

  # GET /rings/1/edit
  def edit
    @ring = Ring.find(params[:id])
  end

  # POST /rings
  # POST /rings.json
  def create
    @ring = Ring.new(params[:ring])

    respond_to do |format|
      if @ring.save
        format.html { redirect_to @ring, notice: 'Ring was successfully created.' }
        format.json { render json: @ring, status: :created, location: @ring }
      else
        format.html { render action: "new" }
        format.json { render json: @ring.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rings/1
  # PUT /rings/1.json
  def update
    @ring = Ring.find(params[:id])

    respond_to do |format|
      if @ring.update_attributes(params[:ring])
        format.html { redirect_to @ring, notice: 'Ring was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ring.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rings/1
  # DELETE /rings/1.json
  def destroy
    @ring = Ring.find(params[:id])
    @ring.destroy

    respond_to do |format|
      format.html { redirect_to rings_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def home
  end

  def faq
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rings_helper.rb
module RingsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spoon Rings</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Spoon Rings", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "About",    '#' %></li>
              <li><%= link_to "FAQ",    '#' %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div id="banner">
    </div>
    <div id="content">
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/rings/_form.html.erb
<%= form_for(@ring) do |f| %>
  <% if @ring.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ring.errors.count, "error") %> prohibited this ring from being saved:</h2>

      <ul>
      <% @ring.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rings/_ring.html.erb
<li class="span3">
  <div class="spoon_thumbnail">
    <p><%= link_to(image_tag(ring.image, class:"album_thumbnail"), ring) %></p>
    <h6><%= ring.name %></h6>
    <p><%= ring.description %></p>
    <p><%= link_to 'Edit', edit_ring_path(ring) %> | <%= link_to 'Destroy', ring, method: :delete, data: { confirm: 'Are you sure?' } %></p>
  </div>
</li>

app/views/rings/edit.html.erb
<h1>Edit Ring</h1>

<%= render 'form' %>

<%= link_to 'Show', @ring %> |
<%= link_to 'Back', rings_path %>

app/views/rings/index.html.erb
<!-- <h2>Listing Rings (<%= @rings.size %>)</h2> -->

<div id="ring-wrapper">
  <ul class="thumbnails">
    <%= render @rings %>
  </ul>
</div>

<%= link_to 'New Ring', new_ring_path %>

app/views/rings/new.html.erb
<h1>New ring</h1>

<%= render 'form' %>

<%= link_to 'Back', rings_path %>

app/views/rings/show.html.erb
<p>
  <%= image_tag(@ring.image) %>
</p>

<p>
  <b>Name:</b>
  <%= @ring.name %>
</p>

<p>
  <b>Description:</b>
  <%= @ring.description %>
</p>

<p>
  <b>Category:</b>
  <%= @ring.category %>
</p>


<%= link_to 'Edit', edit_ring_path(@ring) %> |
<%= link_to 'Back', rings_path %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/faq.html.erb
<h1>StaticPages#faq</h1>
<p>Find me in app/views/static_pages/faq.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Welcome to Spoon Rings</h1>
<p>Check out Chris Ha's <%= link_to 'Latest Rings', rings_path %></p>
<p>
Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quis risus eget urna mollis ornare vel eu leo. Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod.
</p>

</p>
Cras justo odio, dapibus ac facilisis in, egestas eget quam. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Nullam id dolor id nibh ultricies vehicula ut id elit. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Maecenas sed diam eget risus varius blandit sit amet non magna. Nulla vitae elit libero, a pharetra augue. Donec id elit non mi porta gravida at eget metus.
</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br />
    <%= f.text_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :admin %><br />
    <%= f.check_box :admin %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br />
    <%= f.text_field :password_digest %>
  </div>
  <div class="field">
    <%= f.label :remember_token %><br />
    <%= f.text_field :remember_token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Username</th>
    <th>Bio</th>
    <th>Avatar</th>
    <th>Admin</th>
    <th>Password digest</th>
    <th>Remember token</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.username %></td>
    <td><%= user.bio %></td>
    <td><%= user.avatar %></td>
    <td><%= user.admin %></td>
    <td><%= user.password_digest %></td>
    <td><%= user.remember_token %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Bio:</b>
  <%= @user.bio %>
</p>

<p>
  <b>Avatar:</b>
  <%= @user.avatar %>
</p>

<p>
  <b>Admin:</b>
  <%= @user.admin %>
</p>

<p>
  <b>Password digest:</b>
  <%= @user.password_digest %>
</p>

<p>
  <b>Remember token:</b>
  <%= @user.remember_token %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>